//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektAPBD_PiotrPawlaks15182
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pokoj
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pokoj()
        {
            this.Rezerwacja = new HashSet<Rezerwacja>();
        }
    
        public int NrPokoju { get; set; }
        public int IdKategoria { get; set; }
        public int Liczba_miejsc { get; set; }
    
        public virtual Kategoria Kategoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezerwacja> Rezerwacja { get; set; }
    }
}
