//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektAPBD_PiotrPawlaks15182
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezerwacja
    {
        public int IdRezerwacja { get; set; }
        public System.DateTime DataOd { get; set; }
        public System.DateTime DataDo { get; set; }
        public int IdGosc { get; set; }
        public int NrPokoju { get; set; }
        public bool Zaplacona { get; set; }
    
        public virtual Gosc Gosc { get; set; }
        public virtual Pokoj Pokoj { get; set; }
    }
}
